# Generated by Django 5.0.7 on 2024-07-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_address_customuser_biography_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='biography',
            new_name='bio',
        ),
    ]
